def render_calculator(equation: str, result: float):
    print("\n _____________________ ")
    print("|  _________________  |")
    print(f"| | {str(result).ljust(15)} | |")
    print("| |_________________| |")
    print("|  ___ ___ ___   ___  |")
    print("| | 7 | 8 | 9 | | + | |")
    print("| |___|___|___| |___| |")
    print("| | 4 | 5 | 6 | | - | |")
    print("| |___|___|___| |___| |")
    print("| | 1 | 2 | 3 | | * | |")
    print("| |___|___|___| |___| |")
    print("| | 0 | . | = | | / | |")
    print("| |___|___|___| |___| |")
    print("|_____________________|")
    print(f"Equation: {equation}\n")